FROM ae6rt/decap-build-base:latest

RUN curl -o /etc/yum.repos.d/epel-apache-maven.repo https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
RUN yum install -y java-1.7.0-openjdk-devel apache-maven
